# Generated by Django 5.1.7 on 2026-02-12 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('url', models.URLField()),
                ('avg_color', models.CharField(max_length=20)),
                ('src_original', models.URLField()),
                ('src_large2x', models.URLField()),
                ('src_large', models.URLField()),
                ('src_medium', models.URLField()),
                ('src_small', models.URLField()),
                ('src_portrait', models.URLField()),
                ('src_landscape', models.URLField()),
                ('src_tiny', models.URLField()),
                ('alt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
