# Generated by Django 5.1.7 on 2026-02-12 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photographers', '0001_initial'),
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photographers.photographer'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['created_at'], name='photos_phot_created_84134a_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['owner'], name='photos_phot_owner_i_0a50d8_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['avg_color'], name='photos_phot_avg_col_71f102_idx'),
        ),
    ]
